Test case fix
mojitoinc/mojito-core-service pull request #57
Opened 2023-06-08 04:48 UTC by kameshkishoreIonixx

## Related Issue
Test case for signature fixed and Read me update.

## Changes

1. Test case for useSignature
2. Readme update

## Screenshots
![Screenshot from 2023-06-08 10-16-24](https://github.com/mojitoinc/mojito-core-service/assets/103174933/b836efb2-fe52-4c16-bee1-249cdf119535)

## Checklist

- [ ] param and service should be meaningful(name should indicate, why it is used rather than which service its calling.)
- [ ] Param should be type and description in ReadMe
- [ ] don't use arrow function functional components useCallback
- [ ] Always try to use const. There is a very good reason to use let
- [ ] Should be exported only Hooks and interface
- [ ] Before pushing to GitHub delete all unused states, spacing, and console.log, if exist
- [ ] PR should contain  screenshots Unit test with 100% coverage
- [ ] Lint should be passed on to PR

2023-06-08 15:09 UTC, alexinx requested changes

2023-06-08 15:09 UTC, alexinx commented on __test__/hooks/useSignature.test.tsx
> -        try {
I asked to fix the issue. Not remove the test case.

2023-06-08 15:12 UTC, kameshkishoreIonixx commented on __test__/hooks/useSignature.test.tsx
> -        try {
already it was mocked in another case so no need for try catch that's y i removed.

2023-06-09 12:29 UTC, alexinx approved these changes

2023-06-09 12:29 UTC, merged